package com.example.pcstore.model;

public enum Hardware {
    PC, LAPTOP, CONSOLE, COMPONENT,
    CASE, CPU, MOTHERBOARD, RAM, GPU, HARD_DRIVE, PSU, MOUSE, KEYBOARD, MONITOR,
    MINI_ITX, MICRO_ATX, ATX, E_ATX, XL_ATX,
    LGA_1150, LGA_1151, AM3, AM4,
    DDR3, DDR4, DIMM1, DIMM2, DIMM4,
    PCIE3, PCIE4,
    SATA3, M2,
    USB2, USB3, THUNDERPORT,
    HDMI,DVID,VGA,DPORT
}
